// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxVBx0zWF3fTqHwDfxNteErwNuXwM_QdI',
    appId: '1:1096364420562:web:5f6bd1385fd1c654ddec0b',
    messagingSenderId: '1096364420562',
    projectId: 'pawsitive-db781',
    authDomain: 'pawsitive-db781.firebaseapp.com',
    storageBucket: 'pawsitive-db781.appspot.com',
    measurementId: 'G-8T4Q55MB8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8WvQwDboszlVd2jKxTir8_-Zu7snuCws',
    appId: '1:1096364420562:android:fd5e817ecdfd2789ddec0b',
    messagingSenderId: '1096364420562',
    projectId: 'pawsitive-db781',
    storageBucket: 'pawsitive-db781.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE0GAIjrNH-K0RgOGr15f9pk_IBeo-Mzo',
    appId: '1:1096364420562:ios:4bf511f0fbd11f82ddec0b',
    messagingSenderId: '1096364420562',
    projectId: 'pawsitive-db781',
    storageBucket: 'pawsitive-db781.appspot.com',
    iosBundleId: 'com.example.pawsitiveMatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE0GAIjrNH-K0RgOGr15f9pk_IBeo-Mzo',
    appId: '1:1096364420562:ios:4bf511f0fbd11f82ddec0b',
    messagingSenderId: '1096364420562',
    projectId: 'pawsitive-db781',
    storageBucket: 'pawsitive-db781.appspot.com',
    iosBundleId: 'com.example.pawsitiveMatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxVBx0zWF3fTqHwDfxNteErwNuXwM_QdI',
    appId: '1:1096364420562:web:89d20f5470f35858ddec0b',
    messagingSenderId: '1096364420562',
    projectId: 'pawsitive-db781',
    authDomain: 'pawsitive-db781.firebaseapp.com',
    storageBucket: 'pawsitive-db781.appspot.com',
    measurementId: 'G-Z8WN3WKWXX',
  );
}
